name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # 允许手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # 添加权限配置
    permissions:
      contents: read
      pages: write      # 如果需要部署到GitHub Pages
      id-token: write   # 如果需要部署到GitHub Pages
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Build the site in Jekyll container
      run: |
        docker run --rm \
        -v ${{ github.workspace }}:/srv/jekyll \
        -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        -e JEKYLL_ENV=production \
        jekyll/builder:latest \
        /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    
    # 上传构建产物
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: ./_site
    
    # 部署到GitHub Pages
    # - name: Deploy to GitHub Pages
    #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./_site
